# Generated by Django 4.1.6 on 2023-06-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Assortment_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Assortment ID')),
                ('Assort_description', models.CharField(max_length=1000)),
                ('Dimensional_weight1', models.IntegerField(verbose_name='Dimensional Weight')),
                ('Actual_weight1', models.IntegerField(verbose_name='Actual Weight')),
                ('pictures', models.FileField(upload_to='')),
                ('Item_label', models.CharField(max_length=30)),
                ('pictures_item', models.FileField(upload_to='')),
                ('item_pictures', models.FileField(upload_to='', verbose_name='Upload Image')),
                ('items_nums', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')])),
                ('AMOUNT_OF_QTY_SHIPPED', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_loc', models.CharField(choices=[('Ikeja', 'Ikeja'), ('Gbagada', 'Gbagada'), ('Surulere', 'Surulere')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('Campaign_ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Campaign_Name', models.CharField(max_length=200)),
                ('Date_created', models.DateTimeField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Budget', models.IntegerField()),
                ('Actual_cost', models.IntegerField()),
                ('Expected_revenue', models.IntegerField()),
                ('Campaign_objective', models.TextField(max_length=200)),
                ('Campaign_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Address_1', models.CharField(max_length=250, verbose_name='Address')),
                ('Birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designations', models.CharField(choices=[('Customer Service Executive', 'Customer Service Executive'), ('Human Resources', 'Human Resources'), ('Sales Resource', 'Sales Resource'), ('Operations Officer', 'Operations Officer'), ('Marketing Officer', 'Marketing Officer'), ('Management', 'Management')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('Tracking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Escalation', models.CharField(choices=[('MISDECLARATION', 'Misdeclaration'), ('THEFT', 'Theft'), ('Delays', 'Delays'), ('Specify Others', 'Specify Others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tdolcrm.contact')),
                ('Leads', models.CharField(choices=[('Coldcall', 'Coldcall'), ('Campaign', 'Campaign'), ('Email', 'Email'), ('Word of Mouth', 'Word of Mouth'), ('Website', 'Website'), ('Tradeshow', 'Tradeshow'), ('Direct mail', 'Direct mail'), ('Employee referral', 'Employee referral'), ('Self generated', 'Self generated'), ('Existing customer', 'Existing customer'), ('Other', 'Other')], max_length=25, verbose_name='Lead source')),
            ],
            bases=('tdolcrm.contact',),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tdolcrm.contact')),
                ('Nature_of_Business', models.CharField(max_length=50, verbose_name='Nature of Business')),
                ('Nature_of_Shipment', models.CharField(max_length=50)),
                ('Pickup_location', models.CharField(max_length=200)),
                ('NoOfPackages_Monthly', models.IntegerField(verbose_name='No of Packages Monthly')),
                ('Monthly_revenue', models.IntegerField(verbose_name='Monthly Revenue')),
            ],
            bases=('tdolcrm.contact',),
        ),
        migrations.CreateModel(
            name='Sales_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Department')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.department')),
            ],
        ),
        migrations.CreateModel(
            name='Human_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Records',
            fields=[
                ('Employee_ID', models.CharField(default='4', max_length=4, primary_key=True, serialize=False, verbose_name='Employee ID Code')),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Manager_Team', models.CharField(choices=[('Business Manager', 'Business Manager'), ('Business Development Manager', 'Business Develoment Manager')], max_length=35, verbose_name='Manager / Team Lead')),
                ('Employment_date', models.DateField(verbose_name='Hired Date')),
                ('Resumption_date', models.DateField()),
                ('Employment_Validity', models.CharField(choices=[('Probation', 'Probation'), ('Confirmed', 'Confirmed')], max_length=10)),
                ('Employee_branch1', models.CharField(choices=[('Ikeja', 'Ikeja'), ('Gbagada', 'Gbagada'), ('Surulere', 'Surulere')], max_length=15, verbose_name='branch')),
                ('Departmentz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.department', verbose_name='Department')),
                ('Rolez', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.role', verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Service_Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_processed', models.DateTimeField()),
                ('Case_description', models.CharField(max_length=500)),
                ('Case_Categories', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tdolcrm.shipment')),
                ('Shipments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=100)),
                ('Date_created1', models.DateField(verbose_name='Date Created')),
                ('Start_date1', models.DateField(verbose_name='Start Date')),
                ('End_date1', models.DateField(verbose_name=' End Date')),
                ('Activity_description', models.TextField(max_length=300, verbose_name='Activity description')),
                ('Campaign_Activities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.campaign', verbose_name='Campaign Name')),
                ('Employee_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.employee_records', verbose_name='Employee Assigned')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('prospect_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tdolcrm.prospect')),
                ('Customer_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Consignee_Name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('Consignee_Company', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('No_of_packages_monthly', models.IntegerField()),
            ],
            bases=('tdolcrm.prospect',),
        ),
        migrations.CreateModel(
            name='Shipment_order',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tdolcrm.customer')),
                ('Tracking_number', models.CharField(default=1, max_length=18, primary_key=True, serialize=False, verbose_name='Tracking Number')),
                ('Consignee_telephone', models.IntegerField(verbose_name='Consignee Telephone')),
                ('No_of_packages', models.IntegerField()),
                ('Dimensional_weight', models.IntegerField()),
                ('Dimensional_height', models.IntegerField()),
                ('Item_description', models.TextField(max_length=250)),
                ('Customer_signature', models.CharField(max_length=250)),
                ('Branch_of_shipment', models.CharField(choices=[('Ikeja', 'Ikeja'), ('Gbagada', 'Gbagada'), ('Surulere', 'Surulere')], max_length=8, verbose_name='Shipment Branch')),
            ],
            bases=('tdolcrm.customer',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Invoice_date', models.DateTimeField(auto_now_add=True, verbose_name='Invoice Date')),
                ('Shipment_origin', django_countries.fields.CountryField(max_length=2, verbose_name='Shipment Origin')),
                ('No_of_packages1', models.IntegerField(verbose_name='No of Packagees')),
                ('Total_Billable_weight', models.IntegerField(verbose_name='Total Billable Weight')),
                ('Insurances', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Packaging_fee', models.IntegerField()),
                ('Freight_cost', models.IntegerField()),
                ('Total_shipment_cost', models.IntegerField()),
                ('Date_created3', models.DateTimeField(default='2012-09-04 18:00', verbose_name='Date Created')),
                ('AssortmentIDs', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.assortment', verbose_name='Assortment ID')),
                ('Assortment_IDs_Inv', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='tdolcrm.assortment', verbose_name='Assortment ID')),
                ('Tracking_numbers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.shipment', verbose_name='Tracking Number')),
                ('Consignee_Name_inv', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.customer', verbose_name='Sender Name')),
            ],
        ),
        migrations.AddField(
            model_name='assortment',
            name='Customer_Name',
            field=models.OneToOneField(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.customer'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='Consignee_name1',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.shipment_order', verbose_name='consignee Name'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='Shipmentorder1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='tdolcrm.shipment_order', verbose_name='Order ID'),
        ),
        migrations.AddField(
            model_name='assortment',
            name='shipmentorder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='tdolcrm.shipment_order'),
        ),
    ]
