# Generated by Django 4.1.6 on 2023-06-15 16:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tdolcrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_order',
            name='Country_shipment',
            field=django_countries.fields.CountryField(default='', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='No_of_packages_monthly',
            field=models.IntegerField(null=True),
        ),
    ]
