# Generated by Django 4.1.6 on 2023-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdolcrm', '0003_shipment_order_country_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment_order',
            name='Postal_code',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='shipment_order',
            name='Senders_FirstName',
            field=models.CharField(default='', max_length=250, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='shipment_order',
            name='Senders_LastName',
            field=models.CharField(default='', max_length=250, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Address_1',
            field=models.TextField(max_length=250, verbose_name='Address'),
        ),
    ]
